name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: luminous-return-441222-f4
  GKE_CLUSTER: stock-insight-cluster
  GKE_ZONE: us-west1-a
  IMAGE: us-central1-docker.pkg.dev/luminous-return-441222-f4/tradeseer-repo/tradeseer-ai

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          python -m pytest tests/ -v
        fi
      continue-on-error: true

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and Push
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ env.IMAGE }}:${SHORT_SHA} \
          -t ${{ env.IMAGE }}:latest \
          --push .

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }}
    
    - name: Deploy
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        kubectl set image deployment/stock-insight \
          stock-insight=${{ env.IMAGE }}:${SHORT_SHA}
        kubectl rollout status deployment/stock-insight --timeout=5m
    
    - name: Get Status
      run: |
        kubectl get pods -l app=stock-insight
        kubectl get svc stock-insight-service